version: '3.8'

services:
  app:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: app
    environment:
      - BITRATE=${BITRATE}
    volumes:
        - './:/var/www/html/'
